#!/bin/bash -l
#SBATCH --job-name="task7_assign"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks=4             
#SBATCH --cpus-per-task=8        
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --account=uzh8
#SBATCH --output=job_outputs/task10_5_test.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK


module load cray-mpich boost
module load fftw/3.3.10

srun ./assign $SCRATCH/B100.00100 100 3